name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-stable-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-registry-
    - name: Cache Cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-stable-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-cargo-index-
    - name: Cache Cargo build
      uses: actions/cache@v1
      with:
        path: target/debug
        key: ${{ runner.os }}-stable-build-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-stable-build-target-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        NASH_API_SECRET: eyJjaGlsZF9rZXlzIjp7Im0vNDQnLzAnLzAnLzAvMCI6eyJhZGRyZXNzIjoiMk5FdXA2UDV3RmhKbUo2a0NDdFZWRUs4YVl1OU01SHIxWW4iLCJjbGllbnRfc2VjcmV0X3NoYXJlIjoiOTYwYzk5OTBkMDNjMWVhOWM0Njc5ZjhiYjMxNGZhNjkxZTY0YjBjOGZhZTNmZjcyYzFkZDI0MWM2YWViYjVmYyIsInB1YmxpY19rZXkiOiIwMzIyNWU5NTQ1ZjAxODMyNTc3YmI3NDlhZmEzOThlNmVjNmYwY2E3MGViNDE3M2Y1YzQ5YmFjYzdmOGY0YzhiYmEiLCJzZXJ2ZXJfc2VjcmV0X3NoYXJlX2VuY3J5cHRlZCI6IjdhMzM1NGJiYTM2MmEzYzFkNGYzYTJkYjAwMWI5MjliODYxMDg4ODlmNTVhMDYzMmYyNGRiZDczNjhkMjgxNTA5MDE1MDgwZjNkNGVkZThhMzBjYWVlNzcxODAxMTZlNGQ1MzNhNmExZDk3Y2ViNWZmYzZkODI3MWYzYTYzZjE2NmQ2NzZjZWEwYTYxMDUwZTg0OGU4ZGY2MzU5NzU1NDE4OTU4OTBlMWZhMTE1NWJmN2MxODRjNjI2OTUyOWJiMjZjZjgxM2FiZWQ3OWZhMGJlYWY3NDlmZWI4OGE2NmZiZTM5ZWRjNzQ4YzgyZmU4OGQ0NTlhZTdkZTI0MDQ3NmIyNjQxM2I0ZWIyMjhhM2RhYmZlNzEzOTM1NzczODU4MjQwZWI4YzkxNzU3OWFjNzE0ZjFhMDBhN2VlODI3ODc4MzI0YjEyNTZmNDFiNmQ0YzM1MDcwM2ExZjQ2NDQ0NDA4MGVhZWQzYjQ5ZWVjMjFkYTUzNTVjYTk1YTA0ZmZmZTUwNTBiZmMxNzQ3ZTA4ODViMGE3M2M0YTg5NDljZDIwYjcyY2UzMTE2ZWVlYzZkZjI0MTc0MTdiM2I2NzUwYjhkN2VmOTUxMGJjYzFjYzFjYWExNjk5OGQwMGQwMDk3Yjk1NDQ1ZGRkNTg2NGM3ZWNjYjgyZTg4YWRmNTY5NzA5MGVkY2IxMmJiNWNlYTQ4OTUzN2UzZDc0MjUxMTllOTI3NGZjMDI1ZWIwODNkNWE0YWJkMzhiYjdhNGI1NDE2ZTQyYzMzMzIzNTNjYjFlZDYwMjk5ZjYzNzMxNjBjMTljNjhiZWQ1YWU4ODg3NGE1ZmRmNTMxMDdhM2ZhMTVmNjFlYTU2MDFkNzkzNzU1NjdiNTFjMmU0ZWUwNzA3YmMyZDc4N2ZkNjhlOGQ3MTkzNWI4YTFmZmRjMGQyYmEyZWVjYzkyMGYyMjE1N2JjMWMyZmMzMTgyMDJjYTM5MzJhOWI4N2M2NDViNmFlNTBlYjdhYmZkZTBmNWFmNGEzMzI1NzMzOWZjNjFmYTQ0ZGJmODA2Mjg3ZWFjYmQ0YTFkYTc4NWU1ODZjNTBkNmI2MjRjNWNhOTEzZmI5Nzk5ODE5ZDUwZTc3OTg2MmU1OGJjNTk2YTUxMjc4ZmUwY2VmYzNhYzI5MzYzOWQ1ZWE5MjEzNjZlYTExMTIyMjU2ZDE0YzBhMTNlYzZmNTZhNTdhODkzN2EwMzdmZDg2MmFlNzhiNDIxYmVjODg1ZGQ5NmZhY2Y2OTUyYzAwMjU5YWQxOGQ0ZDJlODM3NmU0YzM1YmNiNmMzMWY1ZTNjNTIyZWIyYjAxZWNlYTYzM2MyOTBiMDAxMmNiNDRmOTU1ZjhkM2U1MCJ9LCJtLzQ0Jy82MCcvMCcvMC8wIjp7ImFkZHJlc3MiOiIwMDMzOWM2MGY1NmVhMjVmMThmNTNjMWY0MDE3MGVhNjlmM2NmODdiIiwiY2xpZW50X3NlY3JldF9zaGFyZSI6IjZkZjE5M2I3MjBhMzZlYzZmZTY2ZmRlNmVmMzU3NzQ5ZDkzNDU1YmRjYmU1YTRmOGI2MWY2YzIyZmI5YTllMTMiLCJwdWJsaWNfa2V5IjoiMDQ1YzUzNjg2YjZkMjVlNzgyNTQ1YjM3MDFkY2IzNmJkNGQ3ZmQ3Y2I5ZmJjNDhmMGEzMTZkNzZlOTM4MTFjNjdhMWFlYzRjYjBmMTk2NWNkYWY2ZTBmMDI1NWQwMzFkMmI0NjI5YjUzODZiNmIwNzA2NDYyNDJjMzZkYzZhMzkzMSIsInNlcnZlcl9zZWNyZXRfc2hhcmVfZW5jcnlwdGVkIjoiMTI5NTkzZmU1ZmYwY2YxMThkYWQ3MGJjMDU2MzQ0NDljZGQ5ZTU5OGQ3OTgyYzhhZTE3YjliYmUwMjE2OWJmY2ZmYjdlYThlNmFhYTJiMTYyNzk0ZjkzNjZmNmI0MmI2ODE2OWMwYTI1NDI3MTYwOTgxZTUxMDUyOGM0M2JmNDQ1ZjZmN2I2MDAwMDEzYTBkYTVhYWM5ODg5MmU1YTIzZGVmY2FiNWY0YTEyOWE0YThkMjgyYThlNDZjNWU5Zjg3MGIyMGEzM2E3NTYzYmQ4ZmZlMTc5ZWZlYzY0NDFjOTQ0ZDY1MTEzZDE5ZmZiMmZjZDI0OWVlOTZmYWU2YWU5MWIzMTY3NjU5NjYyODljN2Q4ZGIxMDQ0ODA1YTRkNzg1NzJlMTQwMjk4YmZmMTJhMzc5ODQ2YzUxOTgwM2FiOTNhMzQwOTk1NDdkZTZmNTJlYTA0YTNjNmVmYTg3YjY5YTJhYjUxYmRhNzRjYTkxODZlOGFjNTJkYWQ3Y2ViOGZiYTE2ZTc5NGVmZGU5YWRmZjA3ODgxZDNiNWQwNTQyN2U2M2Q0NzE2YzA2NzVhYzYwYjZkYjU1ZjczOWZjY2FhMDU4YzJjNWUzMDEyYjg3OTc3YjhhOGI5MDFmNjQwMTkwZTEzZWI4MDAyNjU4YmNkMDZiMmFkY2QyNGRlODUyM2JkOTc1MzAzZmNkMTEwYTA0NDA3ZThjM2I2MjZjN2M1Mjk3OTljMjBkMGFiZTQyODFlNTgwNTZkYjI4MzljYWQ3MmMzOThiNDcxYTdkNzQ3Y2NjZTA4MTJlZjc4NzMzNzExYWE3YjA3NDY4ZGU3MTU5NGNmM2ViMTRhYzFiZGNlMDkxOTFlYjViMmFiMmUzNTc5ZDc1MmQ2OTQ0N2FhZDI5YzJhNWQzMjE4ZGY0MDBhZjA3N2FjNTJhNDkyYzUzYzEzZTliYWU5NDhiMDVkYjdlZjUwNTAyMDg4NjBmMTg5MDliMTk2ZmEyZGMwODNjNGMxNzQ2NDJhZWYxODJkYTBmODBlNThhZjM1NDE2MzA0MWRkY2UyNmEwOGFmMmQyNzY0YmVkYTcwMTUyMjc4ZDQ3NDAwNjU3NzEyYzAzYTllYjgxMmQ3NTVkYjZmZjIyZmFhYmFiN2FmMDkwMzA4Y2E0MGNmMmRjMWI2MGIxYTU2YzA0MjUyODgzNzk4ZDUzYTJlN2FkZDA1NmIzYjk5NzZhOGMzYjgwZTg0YjhlZjQ3Yzc4MDdhNGQ2OGUxNDBlMDllM2UzYjUwNmZhOGZiMTc2Njc4MGQ2ODViOTlkZmZlYmZiOWI2Y2VhM2ZhY2QxMmM0ZWQzODRlZTQ0NjI2Mzg1YzY3MWUxODA1ODFiYTUyNyJ9LCJtLzQ0Jy84ODgnLzAnLzAvMCI6eyJhZGRyZXNzIjoiQVZacjVLY1M5RGhRVDg2aEsxZzJicFltaGhweVhHcmNabiIsImNsaWVudF9zZWNyZXRfc2hhcmUiOiI1MTNiNmYxZmJjYTBkMGU5YjA4NjVlZmJhZTU0ZTkxMDcxZWRmYzBiNDBmZDRlZDY2YmY1OTNmNzI3NjA3MTk2IiwicHVibGljX2tleSI6IjAzODhjODk3MThiZTZiNmYwOTExMDUzY2E3NWUyZmY4ZmJkZDE0NDk4NmNmMzg2YmM2NmJiM2EwYTI0ODkyNjk0YSIsInNlcnZlcl9zZWNyZXRfc2hhcmVfZW5jcnlwdGVkIjoiMWE2MzUxNzMyZmYwOWNkNTgxNzBjNjhkNmQ5MGY4YzMzYWZhNTU5ODAyNzUzYTI5NWUxMDAzY2ZkM2FlMWY3NmNkOGQxZmI4NjAzYjhmNGJmNzIxM2U4Njc0ODBmYmE3NTU2YWQzM2UyOTJlNDNhNzY3NjlkNWQzYjgyY2UyYTE1NTg3M2JiOGIxMDI0NTg0NzAxNGFlOWYyNzNjM2FmZDI5NzYzZDFmNzc4OTk2YmRmZGY0YTRhOWYwZTQyNTNlOTZjZTcwOWI5MjJiOGIxOGQ4Y2Q0MDA1ZWZmOWExZWMzNjcwZjczMDIyNmM0NjMzY2ZkMzI2OTFmNGY5YmUxYmQ1ZDZhOTkyZDc1N2IzOTgwZWRjMGQ5NzdmNTY2YWEzYjgyZTFmMzc4NzYxOWNiZmM1YjIwNzNhY2Y4MDYyOThkNjlhMzBjZGRkMzM4ZjJmYWUyNGRiYmFlMzhhZDRjZDJhY2FiMzJhYjUxOWI1ZmVlZDE3MjQxYzE5ZDY5ZGIwN2E0NDEyOWRkZDI5ZTY0ZjY3OThlYjQwYTkyYTdkNzA2NGZhYTY5MTIzODhjMTFiYjFjMzkxNzMwOTk2MzMyMGRiZGEwYjZmNTIyOGY2YzdjMjAzZDM1OGVkMWM4N2NkNGZmZDgwNjAzMDVjNzY5YmVjOTQ1MThmNjAwODNhYzFiYzJiMzJmYmY4MWI5ZDkzMDk3YzQxYWE2YmEwODhlODFhMmYwYzgxNjc0YjYzMzZiNTVmNjFkZGZhMTBiYzA1NjYzNWUwNmZiNWU3YmE0ODYxMmJkYzhhZGZjZDNjMTkzZjExZjc0ZGUzZmMxODQ1Y2I5OGU3MTJlZjU4MzhlNGM5MDc1ODY5YWNlMTNkZjdlMWI5YTg0NWMzZDdlODA3MWVmN2U1ZDJlZWJhYmFjNGJmMTlkNmVkNTE3YzE3NmYyN2JiMzVkNDI0NzhhMGJlNGUzYTk1MThjNWNkYjVhNDU4MDI0MjFlOWE0YTZlZTJmY2M5ZjBmYzBkNjFmNTkzYzNkZDMyODkwNzNhOGI0YzFkYTJjZDM5MWVmNjBmOTBlMDU1MzgxYWY0NzEzM2U1NWI0ODRiZjc0ZDhmOTM5ZjNjOTY0YTEzYWU0MjYwYjc3NjI3OTExODM2Mjk3ZDNlYWVjODJmMGNlNjYwMTY2NjhkZDc0ZGE4NmFiNWNiM2MyMjNkYzNjNTczZjU2OGUyOTQ1ZDZmNTJmMzBkMzNmMjdjMTY2ODlmMzI3Y2EyZjY1N2JjOTk5ODg5YzRiYmEzY2FiZGQ1OGRlYmNlNWQ4YzE4N2IwYmNlNTcyMThhOGI2ZDhlZWI1NWU5NjI3ZmQyNDczOWVhZjE2ZjYyOGQzIn19LCJwYWlsbGllcl9wayI6eyJuIjoiNTk4N2U2MjIyNjFjYWY5NmUyNTgyNmM3MGNmMzIzYjI2MTk0ZmY5Y2ZlNjllM2Y0MGYzMGQzMDY1NzE2NDJjYWVhOGEzMTQzZDExZmY5NGMxMzg4MzYwNDg2NzM1N2FlOGMwZTY2M2JmMDNkMDA5MzAxNmQ3ZjRkNzkwYWUyNGUyOTE3ODAzZDgxMmI2NDFhZjJkNmMwOTU3M2QxMTJlYjc2ODY0NjUyOTFjZDE0NmZkNjYyZjc3ZjU5NWVmODMyNzdiZTE2ODBkMDQwYjFmM2M0OTljODE5MTc1NzIwNmU1MTBhZTU0NzI0ZDY2N2ZjMDQxYTJjN2MyZmYzZDNiNjZjMzcyOWRjMjVlMDJjNDAxOWVkM2EwMTJmZDc1ZWMwZTAzOTQ4Y2Y3ODNhZDM5MDJjZTVlNWU3MjIyOWMzZGQzYTE0YjkzNGQ2MDI2OWFjYjdiYTBiZDQxNWQyZGUxMjhlZjE4NzIyNDAwYmFlYTJlODUwZTZkMWZkODc4N2EwMTMwZDUxNjIwNmQ3MThhNDlkN2EyMWQ0MjhiMGZhMzc3MzA3OWI2NDg2MTgxMTE5MWI1NTAwMWQ0YzJjMjlmNjMwMzE0YmUxOTFjZjNjYTNmMGY4ZTA5ZWUwOTU0M2ZmZGRhM2Y5N2NmMTY5ZDUyZTA2N2NmZDQwY2IzMDM5NDEifSwicGF5bG9hZF9wdWJsaWNfa2V5IjoiMDJjM2UwNjk4YmNiODBlZjFjZDQ0NzVhZjdjNjViOTgwNjA3MWFjZTQzMGQ2YjNkNzJkMTI4OTdhZjc0NTZlYjAxIiwicGF5bG9hZF9zaWduaW5nX2tleSI6IjZiMWVjMmJiZjhhZjcwNDQzZmExNTAyZGU4OGE4NWFjM2VhNjMwZDA4NmJjZjYyNjFiNzEyMWY1NDI3MTgyY2MiLCJ2ZXJzaW9uIjowfQ==
        NASH_API_KEY: 24c6f81b-57b4-407a-ab5c-fe27402b184e
      run: cargo test --release -- --test-threads=1

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  rustfmt_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
